repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Lint and fix Python code"
        entry: poetry run ruff check --fix --force-exclude
        language: system
        types_or: [python]

      - id: ruff-format
        name: ruff-format
        description: "Format Python code"
        entry: poetry run ruff format --force-exclude
        language: system
        types_or: [python]
