services:
  postgres_db:
    image: postgres:15-alpine
    container_name: ${DOCKER_NAME_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network: